import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navComponents = [
  { title: "Home", href: "/" },
  {
    title: "Dashboard",
    href: "/dashboard",
  },
  {
    title: "Classify",
    href: "/classify",
  },
  {
    title: "Upload",
    href: "/upload",
  },
  {
    title: "Login",
    href: "/login",
  },
  {
    title: "Register",
    href: "/register",
  },
];
const NavComponent = () => {
  return (
    <nav>
      <ol style={{ listStyleType: "none", marginBottom: "20px" }}>
        {navComponents.map((component) => {
          return (
            <li
              style={{
                display: "inline-block",
                margin: "4px",
                fontSize: "2rem",
              }}
            >
              <Link href={component.href}>{component.title}</Link>
            </li>
          );
        })}
      </ol>
    </nav>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NavComponent />
        {children}
      </body>
    </html>
  );
}
