import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import logo from "../public/logo.png";
import Image from "next/image";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navComponents = [
  { title: "Home", href: "/" },
  {
    title: "Dashboard",
    href: "/dashboard",
  },
  {
    title: "Login",
    href: "/login",
  },
  {
    title: "Register",
    href: "/register",
  },
];
const NavComponent = () => {
  return (
    <nav className="nav">
      <Link href={navComponents[0].href}>
        <Image
          src={logo}
          alt="logo"
          width={60}
          height={60}
          style={{ borderRadius: 20 }}
        />
      </Link>
      <ul className="list">
        <li>
          <Link href={navComponents[0].href}>{navComponents[0].title}</Link>
        </li>
        <li>
          <Link href={navComponents[1].href}>{navComponents[1].title}</Link>
        </li>
        <li>
          <Link href={navComponents[2].href}>{navComponents[2].title}</Link>
        </li>
        <li>
          <Link href={navComponents[3].href}>{navComponents[3].title}</Link>
        </li>
      </ul>
      <button className="menu">Menu</button>
    </nav>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NavComponent />
        {children}
      </body>
    </html>
  );
}
